remote_theme: pages-themes/architect@v0.2.0
plugins:
- jekyll-remote-theme
title: HabitCorner
description: Habit Corner thrives to assist its user on building a healthy habit/lifestyle. This app is desktop application that will displayed in the corner of your home page.
